export const FETCH_CARDS_SUCCESS = 'FETCH_CARDS_SUCCESS';
export const FETCH_CARDS_ERROR = 'FETCH_CARDS_ERROR';
export const FETCH_CARDS_REQUEST = 'FETCH_CARDS_REQUEST';

export const FLIP_CARD = 'FLIP_CARD';
export const MARK_AS_MATCHED = 'MARK_AS_MATCHED';

export const CHECK_MATCHING_CARDS_START = "CHECK_MATCHING_CARDS_START";
export const CHECK_MATCHING_CARDS_STOP = "CHECK_MATCHING_CARDS_STOP";

export const GAME_VICTORY = "GAME_VICTORY";
